name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_package-unit_test-build_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # editable install of your package
        pip install pytest coverage
        pip install -r docs/requirements.txt

    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report

    - name: Check version consistency
      run: bash scripts/check_version_and_build_docs.sh

    - name: Build documentation
      run: |
        cd docs
        make html
